# Generated by Django 4.1.1 on 2022-10-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0002_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('mensaje', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
