# Generated by Django 4.1.1 on 2022-10-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0003_experiencias_delete_cursos_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencias',
            name='evaluacion',
            field=models.CharField(choices=[('1', 'Bad'), ('2', 'Normal'), ('3', 'Good')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
