# Generated by Django 4.1.1 on 2022-10-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0005_alter_experiencias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='evaluacion',
            field=models.CharField(choices=[('malo', 'Bad'), ('normal', 'Normal'), ('bueno', 'Good')], max_length=6),
        ),
    ]
